In [1]:
import numpy as np

In [5]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [6]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [28]:
np.ones(50)*4

array([4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4.,
       4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4.,
       4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4.])

In [12]:
np.arange(10,51)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50])

In [13]:
np.arange(5)

array([0, 1, 2, 3, 4])

In [14]:
np.arange(1,11)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [15]:
np.arange(1,11,2)

array([1, 3, 5, 7, 9])

In [29]:
np.arange(10,51,2)

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48, 50])

In [33]:
np.arange(6).reshape(2,3)

array([[0, 1, 2],
       [3, 4, 5]])

In [50]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [57]:
np.random.rand(4,3)

array([[[0.31978187, 0.41318449, 0.75790618, 0.74551409, 0.70087761],
        [0.45438638, 0.05068895, 0.48985328, 0.9604659 , 0.54217776],
        [0.63068108, 0.62153619, 0.05600896, 0.09985556, 0.08772382]],

       [[0.03944919, 0.39588353, 0.47452418, 0.3719236 , 0.94160741],
        [0.51449183, 0.00532015, 0.33498306, 0.06344983, 0.67287818],
        [0.82490167, 0.83633332, 0.36588715, 0.5030779 , 0.4841319 ]],

       [[0.52063605, 0.33509081, 0.28337736, 0.77140592, 0.70900874],
        [0.70466441, 0.20252337, 0.90574534, 0.61535949, 0.12039904],
        [0.75998177, 0.05624227, 0.33909519, 0.67080615, 0.4702452 ]],

       [[0.90275976, 0.79414277, 0.01604498, 0.59858933, 0.93742944],
        [0.9765538 , 0.50531518, 0.40232034, 0.9580082 , 0.56159553],
        [0.15343722, 0.7072959 , 0.52442014, 0.54840123, 0.08896524]]])

In [62]:
np.arange(0.01,1.01,0.01).reshape(10,10)

array([[0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 ],
       [0.11, 0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19, 0.2 ],
       [0.21, 0.22, 0.23, 0.24, 0.25, 0.26, 0.27, 0.28, 0.29, 0.3 ],
       [0.31, 0.32, 0.33, 0.34, 0.35, 0.36, 0.37, 0.38, 0.39, 0.4 ],
       [0.41, 0.42, 0.43, 0.44, 0.45, 0.46, 0.47, 0.48, 0.49, 0.5 ],
       [0.51, 0.52, 0.53, 0.54, 0.55, 0.56, 0.57, 0.58, 0.59, 0.6 ],
       [0.61, 0.62, 0.63, 0.64, 0.65, 0.66, 0.67, 0.68, 0.69, 0.7 ],
       [0.71, 0.72, 0.73, 0.74, 0.75, 0.76, 0.77, 0.78, 0.79, 0.8 ],
       [0.81, 0.82, 0.83, 0.84, 0.85, 0.86, 0.87, 0.88, 0.89, 0.9 ],
       [0.91, 0.92, 0.93, 0.94, 0.95, 0.96, 0.97, 0.98, 0.99, 1.  ]])

In [67]:
np.linspace(0,1,20,endpoint=True)

array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])

In [70]:
mat = np.arange(1,26).reshape(5,5)
mat

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [95]:
mat[2:,1:]

array([[12, 13, 14, 15],
       [17, 18, 19, 20],
       [22, 23, 24, 25]])

In [100]:
mat[3:5,2:4]

array([[18, 19],
       [23, 24]])

In [101]:
mat[2:,3:]

array([[14, 15],
       [19, 20],
       [24, 25]])

In [102]:
mat[2:3,2:3]

array([[13]])

In [105]:
mat[3:4,4:]

array([[20]])

In [106]:
mat

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [107]:
mat[0:3,1:2]

array([[ 2],
       [ 7],
       [12]])

In [108]:
mat[4]

array([21, 22, 23, 24, 25])

In [109]:
mat[3:]

array([[16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [110]:
np.sum(mat)

325

In [111]:
np.info(mat)

class:  ndarray
shape:  (5, 5)
strides:  (20, 4)
itemsize:  4
aligned:  True
contiguous:  True
fortran:  False
data pointer: 0x133fd375790
byteorder:  little
byteswap:  False
type: int32


In [112]:
np.std(mat)

7.211102550927978